### ISSUE TITLE
Exception in minerMonkeys.js

### ISSUE THREAD

**Issue by fasiha** [MaiaVictor/WebMonkeys#11]
Very cool project!

I just cloned the repo. Various examples work fine for me, but minerMonkeys.js, in Chrome 52.0.2743.116 (64-bit) and Firefox 48.0.1 (macOS) both, runs the CPU example (`Mined a block on the CPU, nonce: 695822`) but then throws:
```
Uncaught WebMonkeys had the following error from WebGL: ERROR: 0:118: 'nonce' : Loop index cannot be initialized with non-constant expression
```

**Comment by MaiaVictor** [comment]
Woops, silly mistake, should move the addition out of the loop and make it go from 0 to the number of attempts (which is static). Is anyone willing to change this one? I'm quite busy those days...

**Comment by fasiha** [comment]
I'll take a look at it. (Famous last words I know 😆!)
