### ISSUE TITLE
Async processing

### ISSUE THREAD

**Issue by davidmarkclements** [MaiaVictor/WebMonkeys#5]
the offscreencanvas api allows for webgl work in a seperate thread,
it's a little early yet but even if just in node we can do parallell processing
and not block the event loop that could be extremely powerful

**Comment by MaiaVictor** [comment]
Never heard about it, any reference?

**Comment by davidmarkclements** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

As I say, early days, but it would be interesting if there's a way for async processing to work in just node even (without using a second process)
